apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: image-puller
spec:
  selector:
    matchLabels:
      name: image-puller
  template:
    metadata:
      labels:
        name: image-puller
    spec:
      tolerations:
        - key: "node-role.kubernetes.io/control-plane"
          operator: "Exists"
          effect: "NoSchedule"
        - key: "node-role.kubernetes.io/master"
          operator: "Exists"
          effect: "NoSchedule"
      containers:
        - name: processor-prepull
          image: 192.168.1.200:5000/farmonedge-processor:latest
          command:
            [
              "/bin/sh",
              "-c",
              "echo Image pre-pulled, sleeping forever...; sleep infinity",
            ]
