apiVersion: v1
kind: ServiceAccount
metadata:
  name: watcher-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: job-creator-role
rules:
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["create", "get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: watcher-job-creator-binding
subjects:
  - kind: ServiceAccount
    name: watcher-sa
roleRef:
  kind: Role
  name: job-creator-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: watcher
spec:
  replicas: 1
  selector:
    matchLabels:
      app: watcher
  template:
    metadata:
      labels:
        app: watcher
    spec:
      serviceAccountName: watcher-sa
      nodeSelector:
        node-role: master
      tolerations:
        - key: "node-role.kubernetes.io/control-plane"
          operator: "Exists"
          effect: "NoSchedule"
        - key: "node-role.kubernetes.io/master"
          operator: "Exists"
          effect: "NoSchedule"
      containers:
        - name: watcher
          image: 192.168.1.200:5000/farmonedge-watcher:latest
          imagePullPolicy: Always
          env:
            - name: MINIO_ENDPOINT
              value: "minio-service:9000"
            - name: MINIO_ACCESS_KEY
              value: "farmonedge"
            - name: MINIO_SECRET_KEY
              value: "farmonedge"
          volumeMounts:
            - name: job-template-volume
              mountPath: /config
      volumes:
        - name: job-template-volume
          configMap:
            name: job-template-config
